### ISSUE TITLE
Spelling & add info

### ISSUE THREAD

**Issue by EugeneGohh** [Decentraledu/decentraledu-org-website#4]
@SHA888 , can you change the name here:
![Untitled](https://user-images.githubusercontent.com/64187129/122733503-d20b5580-d2af-11eb-91c4-53998ba4f52a.png)

It seems like it should be `decentraledu-org-website` not `decenraledu-org-website`. You missed a `t`.

Also do provide info here too, just suggestion:
![Untitled](https://user-images.githubusercontent.com/64187129/122737805-01bc5c80-d2b4-11eb-897b-a2049cf7601f.png)

**Comment by SHA888** [comment]
Okay got it. Thank you @EugeneGohh
